// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetBook.Core.Data;

#nullable disable

namespace PetBook.Core.Migrations
{
    [DbContext(typeof(PetBookDbContext))]
    partial class PetBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Affenpinscher"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Afghan Hound"
                        },
                        new
                        {
                            Id = 3,
                            Name = "African Hunting Dog"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Airedale Terrier"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Akbash Dog"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Akita"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Alapaha Blue Blood Bulldog"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Alaskan Husky"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Alaskan Malamute"
                        },
                        new
                        {
                            Id = 10,
                            Name = "American Bulldog"
                        },
                        new
                        {
                            Id = 11,
                            Name = "American Bully"
                        },
                        new
                        {
                            Id = 12,
                            Name = "American Eskimo Dog"
                        },
                        new
                        {
                            Id = 13,
                            Name = "American Eskimo Dog (Miniature)"
                        },
                        new
                        {
                            Id = 14,
                            Name = "American Foxhound"
                        },
                        new
                        {
                            Id = 15,
                            Name = "American Pit Bull Terrier"
                        },
                        new
                        {
                            Id = 16,
                            Name = "American Staffordshire Terrier"
                        },
                        new
                        {
                            Id = 17,
                            Name = "American Water Spaniel"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Anatolian Shepherd Dog"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Appenzeller Sennenhund"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Australian Cattle Dog"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Australian Kelpie"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Australian Shepherd"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Australian Terrier"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Azawakh"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Barbet"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Basenji"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Basset Bleu de Gascogne"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Basset Hound"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Beagle"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Bearded Collie"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Beauceron"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Bedlington Terrier"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Belgian Malinois"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Belgian Tervuren"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Bernese Mountain Dog"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Bichon Frise"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Black and Tan Coonhound"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Bloodhound"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Bluetick Coonhound"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Boerboel"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Border Collie"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Border Terrier"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Boston Terrier"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Bouvier des Flandres"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Boxer"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Boykin Spaniel"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Bracco Italiano"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Briard"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Brittany"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Bull Terrier"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Bull Terrier (Miniature)"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Bullmastiff"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Cairn Terrier"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Cane Corso"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Cardigan Welsh Corgi"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Catahoula Leopard Dog"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Caucasian Shepherd (Ovcharka)"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Cavalier King Charles Spaniel"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Chesapeake Bay Retriever"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Chinese Crested"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Chinese Shar-Pei"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Chinook"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Chow Chow"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Clumber Spaniel"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Cocker Spaniel"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Cocker Spaniel (American)"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Coton de Tulear"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Dalmatian"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Doberman Pinscher"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Dogo Argentino"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Dutch Shepherd"
                        },
                        new
                        {
                            Id = 101,
                            Name = "English Setter"
                        },
                        new
                        {
                            Id = 102,
                            Name = "English Shepherd"
                        },
                        new
                        {
                            Id = 103,
                            Name = "English Springer Spaniel"
                        },
                        new
                        {
                            Id = 104,
                            Name = "English Toy Spaniel"
                        },
                        new
                        {
                            Id = 105,
                            Name = "English Toy Terrier"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Eurasier"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Field Spaniel"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Finnish Lapphund"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Finnish Spitz"
                        },
                        new
                        {
                            Id = 113,
                            Name = "French Bulldog"
                        },
                        new
                        {
                            Id = 114,
                            Name = "German Pinscher"
                        },
                        new
                        {
                            Id = 115,
                            Name = "German Shepherd Dog"
                        },
                        new
                        {
                            Id = 116,
                            Name = "German Shorthaired Pointer"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Giant Schnauzer"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Glen of Imaal Terrier"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Golden Retriever"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Gordon Setter"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Great Dane"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Great Pyrenees"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Greyhound"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Griffon Bruxellois"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Harrier"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Havanese"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Irish Setter"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Irish Terrier"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Irish Wolfhound"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Italian Greyhound"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Japanese Chin"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Japanese Spitz"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Keeshond"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Komondor"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Kooikerhondje"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Kuvasz"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Labrador Retriever"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Lagotto Romagnolo"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Lancashire Heeler"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Leonberger"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Lhasa Apso"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Maltese"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Miniature American Shepherd"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Miniature Pinscher"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Miniature Schnauzer"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Newfoundland"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Norfolk Terrier"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Norwich Terrier"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Nova Scotia Duck Tolling Retriever"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Old English Sheepdog"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Olde English Bulldogge"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Papillon"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Pekingese"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Pembroke Welsh Corgi"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Perro de Presa Canario"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Pharaoh Hound"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Plott"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Pomeranian"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Poodle (Miniature)"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Poodle (Toy)"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Pug"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Puli"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Pumi"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Rat Terrier"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Redbone Coonhound"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Rhodesian Ridgeback"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Rottweiler"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Russian Toy"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Saint Bernard"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Saluki"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Samoyed"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Schipperke"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Scottish Deerhound"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Scottish Terrier"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Shetland Sheepdog"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Shiba Inu"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Shih Tzu"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Shiloh Shepherd"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Siberian Husky"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Silky Terrier"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Smooth Fox Terrier"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Soft Coated Wheaten Terrier"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Spanish Water Dog"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Spinone Italiano"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Staffordshire Bull Terrier"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Standard Schnauzer"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Swedish Vallhund"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Thai Ridgeback"
                        },
                        new
                        {
                            Id = 244,
                            Name = "Tibetan Mastiff"
                        },
                        new
                        {
                            Id = 245,
                            Name = "Tibetan Spaniel"
                        },
                        new
                        {
                            Id = 246,
                            Name = "Tibetan Terrier"
                        },
                        new
                        {
                            Id = 248,
                            Name = "Toy Fox Terrier"
                        },
                        new
                        {
                            Id = 250,
                            Name = "Treeing Walker Coonhound"
                        },
                        new
                        {
                            Id = 251,
                            Name = "Vizsla"
                        },
                        new
                        {
                            Id = 253,
                            Name = "Weimaraner"
                        },
                        new
                        {
                            Id = 254,
                            Name = "Welsh Springer Spaniel"
                        },
                        new
                        {
                            Id = 256,
                            Name = "West Highland White Terrier"
                        },
                        new
                        {
                            Id = 257,
                            Name = "Whippet"
                        },
                        new
                        {
                            Id = 258,
                            Name = "White Shepherd"
                        },
                        new
                        {
                            Id = 259,
                            Name = "Wire Fox Terrier"
                        },
                        new
                        {
                            Id = 260,
                            Name = "Wirehaired Pointing Griffon"
                        },
                        new
                        {
                            Id = 261,
                            Name = "Wirehaired Vizsla"
                        },
                        new
                        {
                            Id = 262,
                            Name = "Xoloitzcuintli"
                        },
                        new
                        {
                            Id = 264,
                            Name = "Yorkshire Terrier"
                        });
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ImageId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PetBook.Core.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PetBook.Core.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBook.Core.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PetBook.Core.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.Address", b =>
                {
                    b.HasOne("PetBook.Core.Data.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.Image", b =>
                {
                    b.HasOne("PetBook.Core.Data.Models.Pet", null)
                        .WithMany("Images")
                        .HasForeignKey("PetId");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.Pet", b =>
                {
                    b.HasOne("PetBook.Core.Data.Models.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBook.Core.Data.Models.User", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.User", b =>
                {
                    b.HasOne("PetBook.Core.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBook.Core.Data.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.Pet", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PetBook.Core.Data.Models.User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
